-- USER SQL
CREATE USER CONFIGSERVER IDENTIFIED BY "Welcome1234##";

-- ADD ROLES
GRANT CONNECT TO CONFIGSERVER;
GRANT RESOURCE TO CONFIGSERVER;
ALTER USER CONFIGSERVER DEFAULT ROLE CONNECT,RESOURCE;

-- QUOTA
ALTER USER CONFIGSERVER QUOTA UNLIMITED ON DATA;

-- ENABLE REST
BEGIN
    ORDS.ENABLE_SCHEMA(
            p_enabled => TRUE,
            p_schema => 'CONFIGSERVER',
            p_url_mapping_type => 'BASE_PATH',
            p_url_mapping_pattern => 'configserver',
            p_auto_rest_auth=> TRUE
        );
    commit;
END;
/

CREATE TABLE CONFIGSERVER.PROPERTIES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ) ,
    APPLICATION VARCHAR2 (4000) ,
    PROFILE     VARCHAR2 (4000) ,
    LABEL       VARCHAR2 (4000) ,
    PROP_KEY    VARCHAR2 (4000) NOT NULL,
    VALUE       VARCHAR2 (4000),
    CREATED_ON  TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_BY  VARCHAR2 (100) DEFAULT COALESCE(
        REGEXP_SUBSTR(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'^[^:]*'),
        SYS_CONTEXT('USERENV','SESSION_USER')) NOT NULL,
    UPDATED_ON  TIMESTAMP ,
    UPDATED_BY  VARCHAR2 (100)
) LOGGING;

ALTER TABLE CONFIGSERVER.PROPERTIES
    ADD CONSTRAINT PROPERTIES_PK PRIMARY KEY ( ID )
        USING INDEX LOGGING ;

COMMENT ON TABLE CONFIGSERVER.PROPERTIES IS 'SPRING CLOUD CONFIG SERVER TABLE';

-- CREATE AUDIT TRIGGEER
CREATE OR REPLACE TRIGGER PROPERTIES.AUDIT_TRG BEFORE
    UPDATE ON PROPERTIES
    FOR EACH ROW
BEGIN
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(regexp_substr(sys_context('USERENV', 'CLIENT_IDENTIFIER'), '^[^:]*'), sys_context('USERENV', 'SESSION_USER'));
END;

-- INSERT TEST DATA
INSERT INTO CONFIGSERVER.PROPERTIES (APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE)
VALUES ('atael','dev','latest','test-property','This is the test-property value');
INSERT INTO CONFIGSERVER.PROPERTIES (APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE)
VALUES ('atael','dev','latest','test-property-2','This is the test-property-2 value');
COMMIT;
